// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_1._0_eixo3_2024.Models;

#nullable disable

namespace Projeto_1._0_eixo3_2024.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115161130_M01-AddTableCachorro")]
    partial class M01AddTableCachorro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projeto_1._0_eixo3_2024.Models.Cachorro", b =>
                {
                    b.Property<int>("IdCachorro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCachorro"));

                    b.Property<string>("NascimentoCachorro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCachorro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RacaCachorro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCachorro");

                    b.ToTable("Cachorros");
                });
#pragma warning restore 612, 618
        }
    }
}
